### PR TITLE
add: slot-to-blocktime index + gsfa: store `OffsetAndSizeAndSlot` instead of `OffsetAndSizeAndBlocktime`

### PR DESCRIPTION
**Pull request by gagliardetto**

### CODE REVIEW

**Comment by gagliardetto** [comment]
One last thing: should gsfa also contain whether the tx was successful or not?

**Comment by anjor** [comment]
> One last thing: should gsfa also contain whether the tx was successful or not?

So right now for the stream transactions we parse it out from the error. Don't think we need it in gsfa.

**Review by anjor — APPROVED** [review]

**Comment by gagliardetto** [comment]
by having the success/fail in the gsfa index, we would avoid about 90% of io and cpu time (fetch tx, maybe fetch meta, parse meta)

**Comment by anjor** [comment]
that makes sense. let's add it then.

**Comment by anjor** [comment]
@gagliardetto i am going to merge it. Let's add the success/fail to gsfa index  in a separate PR.

**Pull request merged**
